<?php

namespace AppBundle\Repository;

/**
 * PuzzleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PuzzleRepository extends \Doctrine\ORM\EntityRepository
{
}
