about:
    path: /about
    defaults:
        _controller:  FrameworkBundle:Template:template
        template:     'static/about.html.twig'
        maxAge:       86400
        sharedAge:    86400

app_puzzle:
    resource: "@AppBundle/Controller/PuzzleController.php"
    type:     annotation

fos_user:
    prefix: "user"
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

default:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation

page:
    resource: "@AppBundle/Controller/PageController.php"
    type:     annotation

picture:
    resource: "@AppBundle/Controller/PictureController.php"
    type:     annotation

category:
    resource: "@AppBundle/Controller/CategoryController.php"
    type:     annotation

